name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: randomquotes-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '347.0.0'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: randomquotes-app

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Build the Docker image
    - name: Build
      run: make build-docker
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: make push-docker
    - name: Deploy
      run: make deploy-docker